services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5480:5432"
    environment:
      - POSTGRES_PASSWORD=fluxchat
      - POSTGRES_USER=fluxchat
      - POSTGRES_DB=fluxchat
    networks:
      - my_network

  backend:
    build:
      context: ./flux-chat-backend/.
      dockerfile: Dockerfile
    container_name: backend-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fluxchat
      DB_USER: fluxchat
      DB_PASSWORD: fluxchat
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    ports:
       - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./flux-chat-front
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data: # Docker-managed volume for database
    driver: local